// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LadderResources
{
        public const string achievement_baby_steps = "CgkI9dTc4PwWEAIQAQ"; // <GPGSID>
        public const string achievement_slippery_steps = "CgkI9dTc4PwWEAIQDA"; // <GPGSID>
        public const string leaderboard_ladderboard = "CgkI9dTc4PwWEAIQBw"; // <GPGSID>
        public const string achievement_step_it_off = "CgkI9dTc4PwWEAIQBQ"; // <GPGSID>
        public const string achievement_step_bye_step = "CgkI9dTc4PwWEAIQCw"; // <GPGSID>
        public const string achievement_bigfoot = "CgkI9dTc4PwWEAIQBg"; // <GPGSID>
        public const string achievement_going_up_the_ladderboard = "CgkI9dTc4PwWEAIQCQ"; // <GPGSID>
        public const string achievement_up__up = "CgkI9dTc4PwWEAIQCg"; // <GPGSID>
        public const string achievement_snakes__ladders = "CgkI9dTc4PwWEAIQDQ"; // <GPGSID>
        public const string achievement_ladder_makes_me_madder = "CgkI9dTc4PwWEAIQCA"; // <GPGSID>
        public const string achievement_stepping_up_your_game = "CgkI9dTc4PwWEAIQAw"; // <GPGSID>
        public const string achievement_ladder_to_the_galaxy = "CgkI9dTc4PwWEAIQDg"; // <GPGSID>
        public const string achievement_steep_stooper = "CgkI9dTc4PwWEAIQBA"; // <GPGSID>

}

